version: "3.9"

services:
  django_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_app
    env_file:
      - ./.env.dev
    volumes:
      - ./app/:/usr/src/app/
      - static_vol:/app/static
      - media_vol:/app/media
    # ports:
    #   - "8000:8000"
    expose:
      - 8000
    depends_on:
    - db
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_vol:/app/static
      - media_vol:/app/media
    ports:
      - "8000:80"
    depends_on:
      - django_web
  db:
    image: postgres:alpine3.17
    container_name: django_db_rabinweb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  static_vol:
  media_vol:
  postgres-data: